#############################################################################
# Makefile for building: musicLibrary
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  musicLibrary.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile musicLibrary.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = musicLibrary1.0.0
DISTDIR = /home/peccher/Desktop/PROGETTO\ P2\ MIO/musicLibrary2/.tmp/musicLibrary1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		brano.cpp \
		durata.cpp \
		utentefree.cpp \
		utentegold.cpp \
		utentesilver.cpp \
		utente.cpp \
		loginwidget.cpp \
		userwindow.cpp \
		registerwidget.cpp \
		tablemodeltracks.cpp \
		sessione.cpp \
		tabletracksview.cpp \
		detailswidget.cpp \
		adminwindow.cpp \
		tableusersview.cpp \
		userstablemodel.cpp \
		tracksearchwidget.cpp \
		usersearchwidget.cpp \
		utenteadmin.cpp \
		newtrackwidget.cpp \
		modifyuserwidget.cpp qrc_resource.cpp \
		moc_loginwidget.cpp \
		moc_userwindow.cpp \
		moc_registerwidget.cpp \
		moc_tablemodeltracks.cpp \
		moc_tabletracksview.cpp \
		moc_detailswidget.cpp \
		moc_adminwindow.cpp \
		moc_tableusersview.cpp \
		moc_userstablemodel.cpp \
		moc_tracksearchwidget.cpp \
		moc_usersearchwidget.cpp \
		moc_newtrackwidget.cpp \
		moc_modifyuserwidget.cpp
OBJECTS       = main.o \
		brano.o \
		durata.o \
		utentefree.o \
		utentegold.o \
		utentesilver.o \
		utente.o \
		loginwidget.o \
		userwindow.o \
		registerwidget.o \
		tablemodeltracks.o \
		sessione.o \
		tabletracksview.o \
		detailswidget.o \
		adminwindow.o \
		tableusersview.o \
		userstablemodel.o \
		tracksearchwidget.o \
		usersearchwidget.o \
		utenteadmin.o \
		newtrackwidget.o \
		modifyuserwidget.o \
		qrc_resource.o \
		moc_loginwidget.o \
		moc_userwindow.o \
		moc_registerwidget.o \
		moc_tablemodeltracks.o \
		moc_tabletracksview.o \
		moc_detailswidget.o \
		moc_adminwindow.o \
		moc_tableusersview.o \
		moc_userstablemodel.o \
		moc_tracksearchwidget.o \
		moc_usersearchwidget.o \
		moc_newtrackwidget.o \
		moc_modifyuserwidget.o
DIST          = log \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		musicLibrary.pro durata.h \
		brano.h \
		utente.h \
		utentefree.h \
		utentegold.h \
		utentesilver.h \
		sessione.h \
		loginwidget.h \
		userwindow.h \
		registerwidget.h \
		tablemodeltracks.h \
		tabletracksview.h \
		detailswidget.h \
		adminwindow.h \
		tableusersview.h \
		userstablemodel.h \
		tracksearchwidget.h \
		usersearchwidget.h \
		utenteadmin.h \
		newtrackwidget.h \
		modifyuserwidget.h main.cpp \
		brano.cpp \
		durata.cpp \
		utentefree.cpp \
		utentegold.cpp \
		utentesilver.cpp \
		utente.cpp \
		loginwidget.cpp \
		userwindow.cpp \
		registerwidget.cpp \
		tablemodeltracks.cpp \
		sessione.cpp \
		tabletracksview.cpp \
		detailswidget.cpp \
		adminwindow.cpp \
		tableusersview.cpp \
		userstablemodel.cpp \
		tracksearchwidget.cpp \
		usersearchwidget.cpp \
		utenteadmin.cpp \
		newtrackwidget.cpp \
		modifyuserwidget.cpp
QMAKE_TARGET  = musicLibrary
DESTDIR       = 
TARGET        = musicLibrary


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: musicLibrary.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		musicLibrary.pro \
		resource.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile musicLibrary.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
musicLibrary.pro:
resource.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile musicLibrary.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resource.qrc $(DISTDIR)/
	$(COPY_FILE) --parents durata.h brano.h utente.h utentefree.h utentegold.h utentesilver.h sessione.h loginwidget.h userwindow.h registerwidget.h tablemodeltracks.h tabletracksview.h detailswidget.h adminwindow.h tableusersview.h userstablemodel.h tracksearchwidget.h usersearchwidget.h utenteadmin.h newtrackwidget.h modifyuserwidget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp brano.cpp durata.cpp utentefree.cpp utentegold.cpp utentesilver.cpp utente.cpp loginwidget.cpp userwindow.cpp registerwidget.cpp tablemodeltracks.cpp sessione.cpp tabletracksview.cpp detailswidget.cpp adminwindow.cpp tableusersview.cpp userstablemodel.cpp tracksearchwidget.cpp usersearchwidget.cpp utenteadmin.cpp newtrackwidget.cpp modifyuserwidget.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		files/addusericon.png \
		files/removeusericon.png \
		files/removetrackicon.png \
		files/headphone.png \
		files/modifyusericon.png \
		files/addtrackicon.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_moc_header_make_all: moc_loginwidget.cpp moc_userwindow.cpp moc_registerwidget.cpp moc_tablemodeltracks.cpp moc_tabletracksview.cpp moc_detailswidget.cpp moc_adminwindow.cpp moc_tableusersview.cpp moc_userstablemodel.cpp moc_tracksearchwidget.cpp moc_usersearchwidget.cpp moc_newtrackwidget.cpp moc_modifyuserwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_loginwidget.cpp moc_userwindow.cpp moc_registerwidget.cpp moc_tablemodeltracks.cpp moc_tabletracksview.cpp moc_detailswidget.cpp moc_adminwindow.cpp moc_tableusersview.cpp moc_userstablemodel.cpp moc_tracksearchwidget.cpp moc_usersearchwidget.cpp moc_newtrackwidget.cpp moc_modifyuserwidget.cpp
moc_loginwidget.cpp: sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		userwindow.h \
		tracksearchwidget.h \
		tablemodeltracks.h \
		detailswidget.h \
		tabletracksview.h \
		adminwindow.h \
		registerwidget.h \
		newtrackwidget.h \
		modifyuserwidget.h \
		tableusersview.h \
		userstablemodel.h \
		usersearchwidget.h \
		loginwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include loginwidget.h -o moc_loginwidget.cpp

moc_userwindow.cpp: tracksearchwidget.h \
		tablemodeltracks.h \
		brano.h \
		durata.h \
		sessione.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		detailswidget.h \
		tabletracksview.h \
		userwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include userwindow.h -o moc_userwindow.cpp

moc_registerwidget.cpp: registerwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include registerwidget.h -o moc_registerwidget.cpp

moc_tablemodeltracks.cpp: brano.h \
		durata.h \
		sessione.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		tablemodeltracks.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tablemodeltracks.h -o moc_tablemodeltracks.cpp

moc_tabletracksview.cpp: tabletracksview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tabletracksview.h -o moc_tabletracksview.cpp

moc_detailswidget.cpp: sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		detailswidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include detailswidget.h -o moc_detailswidget.cpp

moc_adminwindow.cpp: sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		registerwidget.h \
		newtrackwidget.h \
		tracksearchwidget.h \
		tablemodeltracks.h \
		modifyuserwidget.h \
		tabletracksview.h \
		tableusersview.h \
		userstablemodel.h \
		usersearchwidget.h \
		adminwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include adminwindow.h -o moc_adminwindow.cpp

moc_tableusersview.cpp: tableusersview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tableusersview.h -o moc_tableusersview.cpp

moc_userstablemodel.cpp: utente.h \
		brano.h \
		durata.h \
		sessione.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		userstablemodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include userstablemodel.h -o moc_userstablemodel.cpp

moc_tracksearchwidget.cpp: tablemodeltracks.h \
		brano.h \
		durata.h \
		sessione.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		tracksearchwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tracksearchwidget.h -o moc_tracksearchwidget.cpp

moc_usersearchwidget.cpp: sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		userstablemodel.h \
		usersearchwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include usersearchwidget.h -o moc_usersearchwidget.cpp

moc_newtrackwidget.cpp: newtrackwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include newtrackwidget.h -o moc_newtrackwidget.cpp

moc_modifyuserwidget.cpp: modifyuserwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/peccher/Desktop/PROGETTO P2 MIO/musicLibrary2' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include modifyuserwidget.h -o moc_modifyuserwidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp loginwidget.h \
		sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		userwindow.h \
		tracksearchwidget.h \
		tablemodeltracks.h \
		detailswidget.h \
		tabletracksview.h \
		adminwindow.h \
		registerwidget.h \
		newtrackwidget.h \
		modifyuserwidget.h \
		tableusersview.h \
		userstablemodel.h \
		usersearchwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

brano.o: brano.cpp brano.h \
		durata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brano.o brano.cpp

durata.o: durata.cpp durata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o durata.o durata.cpp

utentefree.o: utentefree.cpp utentefree.h \
		utente.h \
		brano.h \
		durata.h \
		sessione.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utentefree.o utentefree.cpp

utentegold.o: utentegold.cpp utentegold.h \
		utente.h \
		brano.h \
		durata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utentegold.o utentegold.cpp

utentesilver.o: utentesilver.cpp utentesilver.h \
		utente.h \
		brano.h \
		durata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utentesilver.o utentesilver.cpp

utente.o: utente.cpp utente.h \
		brano.h \
		durata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utente.o utente.cpp

loginwidget.o: loginwidget.cpp loginwidget.h \
		sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		userwindow.h \
		tracksearchwidget.h \
		tablemodeltracks.h \
		detailswidget.h \
		tabletracksview.h \
		adminwindow.h \
		registerwidget.h \
		newtrackwidget.h \
		modifyuserwidget.h \
		tableusersview.h \
		userstablemodel.h \
		usersearchwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwidget.o loginwidget.cpp

userwindow.o: userwindow.cpp userwindow.h \
		tracksearchwidget.h \
		tablemodeltracks.h \
		brano.h \
		durata.h \
		sessione.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		detailswidget.h \
		tabletracksview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userwindow.o userwindow.cpp

registerwidget.o: registerwidget.cpp registerwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registerwidget.o registerwidget.cpp

tablemodeltracks.o: tablemodeltracks.cpp tablemodeltracks.h \
		brano.h \
		durata.h \
		sessione.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tablemodeltracks.o tablemodeltracks.cpp

sessione.o: sessione.cpp sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sessione.o sessione.cpp

tabletracksview.o: tabletracksview.cpp tabletracksview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tabletracksview.o tabletracksview.cpp

detailswidget.o: detailswidget.cpp detailswidget.h \
		sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detailswidget.o detailswidget.cpp

adminwindow.o: adminwindow.cpp adminwindow.h \
		sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		registerwidget.h \
		newtrackwidget.h \
		tracksearchwidget.h \
		tablemodeltracks.h \
		modifyuserwidget.h \
		tabletracksview.h \
		tableusersview.h \
		userstablemodel.h \
		usersearchwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminwindow.o adminwindow.cpp

tableusersview.o: tableusersview.cpp tableusersview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tableusersview.o tableusersview.cpp

userstablemodel.o: userstablemodel.cpp userstablemodel.h \
		utente.h \
		brano.h \
		durata.h \
		sessione.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userstablemodel.o userstablemodel.cpp

tracksearchwidget.o: tracksearchwidget.cpp tracksearchwidget.h \
		tablemodeltracks.h \
		brano.h \
		durata.h \
		sessione.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tracksearchwidget.o tracksearchwidget.cpp

usersearchwidget.o: usersearchwidget.cpp usersearchwidget.h \
		sessione.h \
		brano.h \
		durata.h \
		utente.h \
		utentefree.h \
		utentesilver.h \
		utentegold.h \
		utenteadmin.h \
		userstablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usersearchwidget.o usersearchwidget.cpp

utenteadmin.o: utenteadmin.cpp utenteadmin.h \
		utente.h \
		brano.h \
		durata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utenteadmin.o utenteadmin.cpp

newtrackwidget.o: newtrackwidget.cpp newtrackwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newtrackwidget.o newtrackwidget.cpp

modifyuserwidget.o: modifyuserwidget.cpp modifyuserwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modifyuserwidget.o modifyuserwidget.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

moc_loginwidget.o: moc_loginwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginwidget.o moc_loginwidget.cpp

moc_userwindow.o: moc_userwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userwindow.o moc_userwindow.cpp

moc_registerwidget.o: moc_registerwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registerwidget.o moc_registerwidget.cpp

moc_tablemodeltracks.o: moc_tablemodeltracks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tablemodeltracks.o moc_tablemodeltracks.cpp

moc_tabletracksview.o: moc_tabletracksview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tabletracksview.o moc_tabletracksview.cpp

moc_detailswidget.o: moc_detailswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_detailswidget.o moc_detailswidget.cpp

moc_adminwindow.o: moc_adminwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminwindow.o moc_adminwindow.cpp

moc_tableusersview.o: moc_tableusersview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tableusersview.o moc_tableusersview.cpp

moc_userstablemodel.o: moc_userstablemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userstablemodel.o moc_userstablemodel.cpp

moc_tracksearchwidget.o: moc_tracksearchwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tracksearchwidget.o moc_tracksearchwidget.cpp

moc_usersearchwidget.o: moc_usersearchwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usersearchwidget.o moc_usersearchwidget.cpp

moc_newtrackwidget.o: moc_newtrackwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newtrackwidget.o moc_newtrackwidget.cpp

moc_modifyuserwidget.o: moc_modifyuserwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modifyuserwidget.o moc_modifyuserwidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

